apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service-db

  template:
    metadata:
      labels:
        app: booking-service-db
    spec:
      containers:
        - name: mysql
          image: mysql:8
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: kubernetes-secrets
                  key: BOOKING_DB_USERNAME
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
               secretKeyRef:
                 name: kubernetes-secrets
                 key: BOOKING_DB_ROOT_PASSWORD

            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kubernetes-secrets
                  key: BOOKING_DB_PASSWORD

            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: kubernetes-secrets
                  key: BOOKING_DB_NAME


          ports:
            - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: booking-service-db
spec:
  selector:
    app: booking-service-db
  ports:
    - port: 3306
      targetPort: 3306

