name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  schedule:
      - cron: "0 0 * * 6"

jobs:
  valeriatester:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        java: [21]




    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: Booking-service
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

#    steps:
#      - name: Start docker system
#        run: docker compose up -d --build
#      - name: Sleep 30 s
#        run: sleep 30
#      - name: test endpoint i booking service
#        run: curl - f http://localhost:8082/reservation
#      - name: shut down all
#        if: always()
#        run: docker compose dom -v

      #Checkout code
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Build and run tests
        run: mvn -B package
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/${{secrets.DATABASE_NAME}}
          BOOKING_DB_USER: ${{secrets.BOOKING_DB_USER}}
          BOOKING_DB_PASS: ${{secrets.BOOKING_DB_PASS}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
